lang_name: "Türkçe"
title: "Dayanışma kazanacak!"
subtitle: "Mültecilere Yönelik Saldırılara Karşı Birlikte!"
demo_on: "Gösteri"
date: "8 Şubat 2025"
time: "13:00"
location: "At Steindamm 45"
start: "Start"
end: "End"
speeches: "Speeches"
direction: ltr
date_format: "%b %e, %Y"