lang_name: "Français"
title: "La solidarité vaincra !"
subtitle: "Unis contre les attaques contre les réfugiés !"
demo_on: "Manifestation le"
date: "8 février 2025"
time: "13:00"
location: "At Steindamm 45"
start: "Début"
end: "Fin"
speeches: "Discours intermédiaire"
direction: ltr
date_format: "%b %e, %Y"