lang_name: "عربي"
title: "التضامن سينتصر!"
subtitle: "معاً ضد الهجمات على اللاجئين!"
demo_on: "Demonstration"
date: "February 8th 25"
time: "1pm"
location: "At Steindamm 45"
start: "Start"
end: "End"
speeches: "Speeches"
direction: rtl
date_format: "%b %e, %Y"