lang_name: "Deutsch"
title: "Solidarity will win!"
subtitle: "Zusammen gegen die Angriffe auf Geflüchtete!"
demo_on: "Demonstration am"
date: "08. Februar 2025"
time: "13:00 Uhr"
location: "Am Steindamm 45"
direction: ltr
date_format: "%e. %b %Y"