lang_name: "English"
title: "Solidarity will win!"
subtitle: "United against attacks on refugees!"
demo_on: "Demonstration on"
date: "February 8th 2025"
time: "1pm"
location: "At Steindamm 45"
start: "Start"
end: "End"
speeches: "Speeches"
direction: ltr
date_format: "%b %e, %Y"