lang_name: "English"
title: "Solidarity will win!"
subtitle: "United against attacks on refugees!"
date: "February 8th 25"
time: "1pm"
location: "At Steindamm 45"
direction: ltr
date_format: "%b %e, %Y"