lang_name: "فارسی"
title: "‫همبستگی‬‫پیروز‬ ‫خواهد‬ ‫شد‬"
subtitle: "‫متحد‬‫علیه‬ ‫حمالت‬ ‫بر‬ ‫پناهجویان‬"
demo_on: "Demonstration"
date: "February 8th 25"
time: "1pm"
location: "At Steindamm 45"
direction: rtl
date_format: "%b %e, %Y"